import type { Cert, Kind, Roadmap, ExpLevel, CertLink } from "./types";

const AWS_GUIDES =
  "https://docs.aws.amazon.com/ja_jp/aws-certification/latest/examguides/aws-certification-exam-guides.html";
const AWS_DOCS = "https://docs.aws.amazon.com/ja_jp/";
const IPA_TOP = "https://www.ipa.go.jp/shiken/";

const awsLinks = (slug: string): CertLink[] => [
  { label: "認定ページ・申込", url: `https://aws.amazon.com/jp/certification/${slug}/`, apply: true },
  { label: "試験ガイド", url: AWS_GUIDES },
  { label: "AWS ドキュメント", url: AWS_DOCS },
];
const ipaLinks = (code: string): CertLink[] => [
  { label: "試験区分ページ", url: `https://www.ipa.go.jp/shiken/kubun/${code}.html`, apply: true },
  { label: "試験情報トップ", url: IPA_TOP },
];

export const CERTS: Record<string, Cert> = {
  IPA_FE: { name: "基本情報技術者試験", org: "IPA", level: "基礎", hours: 150, fee: "7,500円", links: ipaLinks("fe"),
    desc: "IT全般の土台を測る国家試験。アルゴリズム・ネットワーク・DB・マネジメントまで広く浅く問われる。",
    topics: ["基礎理論・アルゴリズム", "コンピュータ構成", "ネットワーク基礎", "データベース基礎", "セキュリティ基礎", "マネジメント・ストラテジ"] },
  IPA_AP: { name: "応用情報技術者試験", org: "IPA", level: "中級", hours: 200, fee: "7,500円", links: ipaLinks("ap"),
    desc: "午後の記述式で設計・運用の判断力を問う。高度区分（NW・DB・SC など）への足がかり。",
    topics: ["システムアーキテクチャ", "ネットワーク設計", "データベース設計", "情報セキュリティ", "プロジェクトマネジメント", "経営戦略・監査"] },
  IPA_SG: { name: "情報セキュリティマネジメント試験", org: "IPA", level: "基礎", hours: 80, fee: "7,500円", links: ipaLinks("sg"),
    desc: "利用者側の視点でセキュリティ管理を学ぶ。用語と法令の整理に向く入口。",
    topics: ["情報セキュリティ管理", "リスクアセスメント", "関連法規・ガイドライン", "技術的対策の基礎", "インシデント対応"] },
  IPA_SC: { name: "情報処理安全確保支援士（SC）", org: "IPA", level: "上級", hours: 250, fee: "7,500円", links: ipaLinks("sc"),
    desc: "セキュリティ設計・分析の国家資格。登録すれば士業として名乗れる。",
    topics: ["暗号・認証技術", "セキュアプログラミング", "ネットワークセキュリティ", "インシデントレスポンス", "監査・法令", "午後記述の解答戦略"] },
  IPA_NW: { name: "ネットワークスペシャリスト（NW）", org: "IPA", level: "上級", hours: 250, fee: "7,500円", links: ipaLinks("nw"),
    desc: "国内で最も評価されるネットワーク設計系の高度試験。設計根拠を文章で説明する力が要る。",
    topics: ["ルーティング・スイッチング", "TCP/IP 詳細", "冗長化・高可用性設計", "無線・WAN 技術", "DNS/DHCP 設計", "午後記述の解答戦略"] },
  IPA_DB: { name: "データベーススペシャリスト（DB）", org: "IPA", level: "上級", hours: 250, fee: "7,500円", links: ipaLinks("db"),
    desc: "論理・物理設計と性能設計を扱う高度試験。データモデリングの精度が問われる。",
    topics: ["正規化・データモデリング", "SQL 応用", "トランザクション制御", "性能設計・チューニング", "バックアップ・リカバリ", "午後記述の解答戦略"] },
  IPA_SA: { name: "システムアーキテクト（SA）", org: "IPA", level: "上級", hours: 250, fee: "7,500円", links: ipaLinks("sa"),
    desc: "要件をアーキテクチャに落とす力を問う。論文試験があり、経験の言語化が鍵。",
    topics: ["要件定義・業務分析", "アーキテクチャ設計", "非機能要件の設計", "移行・運用設計", "論文の型づくり", "事例ストックの整理"] },

  AWS_CLF: { name: "AWS Certified Cloud Practitioner", org: "AWS", level: "基礎", hours: 40, fee: "100 USD",
    links: awsLinks("certified-cloud-practitioner"),
    desc: "AWS の全体像と料金・サポートの考え方をつかむ入口。非エンジニアにも開かれた範囲。",
    topics: ["クラウドの概念", "主要サービス概観", "セキュリティと責任共有モデル", "料金・請求・サポート"] },
  AWS_SAA: { name: "AWS Certified Solutions Architect – Associate", org: "AWS", level: "中級", hours: 100, fee: "150 USD",
    links: awsLinks("certified-solutions-architect-associate"),
    desc: "可用性・コスト・セキュリティを踏まえた構成を選ぶ力を問う、AWS 資格の中心的な一枚。",
    topics: ["VPC とネットワーキング", "EC2・オートスケーリング", "S3 とストレージ設計", "RDS・DynamoDB", "IAM と権限設計", "疎結合アーキテクチャ"] },
  AWS_SOA: { name: "AWS Certified CloudOps Engineer – Associate", org: "AWS", level: "中級", hours: 110, fee: "150 USD",
    links: awsLinks("certified-cloudops-engineer-associate"),
    notice: "旧 SysOps Administrator – Associate の後継（SOA-C03）。旧試験の受験はすでに終了しています。",
    desc: "運用・監視・自動化の視点。CloudWatch と IaC の実務感覚がそのまま点に変わる。",
    topics: ["CloudWatch 監視・アラーム", "デプロイと自動化", "CloudFormation", "バックアップ・復旧", "コスト最適化", "トラブルシューティング"] },
  AWS_SAP: { name: "AWS Certified Solutions Architect – Professional", org: "AWS", level: "上級", hours: 200, fee: "300 USD",
    links: awsLinks("certified-solutions-architect-professional"),
    desc: "複数アカウント・ハイブリッド・移行まで含む大規模設計。長文シナリオの読解が本番。",
    topics: ["マルチアカウント戦略", "ハイブリッド接続設計", "移行戦略（7R）", "コスト最適化設計", "災害対策・RTO/RPO", "長文設問の読解手順"] },
  AWS_ANS: { name: "AWS Certified Advanced Networking – Specialty", org: "AWS", level: "専門", hours: 180, fee: "300 USD",
    links: awsLinks("certified-advanced-networking-specialty"),
    notice: "この試験は廃止予定です。最終受験日は 2026年8月25日と案内されています。受験予定がある場合は公式ページで最新の日程を確認してください。",
    desc: "AWS 資格の中でも屈指の難度。オンプレ側のネットワーク知識がそのまま効く。",
    topics: ["VPC 設計・ルーティング", "Transit Gateway", "Direct Connect", "BGP とルート制御", "Route 53 の複合構成", "ハイブリッドDNS設計"] },
  AWS_SCS: { name: "AWS Certified Security – Specialty", org: "AWS", level: "専門", hours: 150, fee: "300 USD",
    links: awsLinks("certified-security-specialty"),
    desc: "鍵管理・検知・インシデント対応まで。IAM の細部を詰めるほど楽になる。",
    topics: ["IAM ポリシー詳細", "KMS と暗号化", "GuardDuty・Security Hub", "ログ設計と証跡", "インシデント対応", "ネットワーク保護"] },
  AWS_MLA: { name: "AWS Certified Machine Learning Engineer – Associate", org: "AWS", level: "中級", hours: 120, fee: "150 USD",
    links: awsLinks("certified-machine-learning-engineer-associate"),
    desc: "モデルの実装より、データ基盤と運用（MLOps）に重心がある。",
    topics: ["データ準備・特徴量", "SageMaker の使い分け", "モデル評価", "デプロイと監視", "セキュリティとコスト"] },

  LINUC1: { name: "LinuC レベル1", org: "LPI-Japan", level: "基礎", hours: 90, fee: "16,500円 × 2試験",
    links: [{ label: "LinuC 公式サイト", url: "https://linuc.org/", apply: true }],
    desc: "Linux 運用の基礎を体系化。手が動く人ほど短期で通る。",
    topics: ["シェルとコマンド操作", "パッケージ管理", "ファイルシステム・権限", "プロセス管理", "ネットワーク設定", "systemd と起動処理"] },
  TF_ASSOC: { name: "HashiCorp Certified: Terraform Associate", org: "HashiCorp", level: "中級", hours: 50, fee: "70.5 USD",
    links: [{ label: "認定ページ・申込", url: "https://developer.hashicorp.com/certifications/infrastructure-automation", apply: true },
            { label: "Terraform ドキュメント", url: "https://developer.hashicorp.com/terraform/docs" }],
    desc: "IaC の考え方と Terraform の作法。学習コストの割にリターンが大きい一枚。",
    topics: ["HCL の基本文法", "state の扱い", "モジュール設計", "プロバイダとバックエンド", "ワークフローとCI連携"] },
  CKA: { name: "Certified Kubernetes Administrator（CKA）", org: "CNCF", level: "中級", hours: 120, fee: "445 USD",
    links: [{ label: "認定ページ・申込", url: "https://www.cncf.io/training/certification/cka/", apply: true },
            { label: "Kubernetes ドキュメント", url: "https://kubernetes.io/ja/docs/home/" }],
    desc: "実機操作のみの試験。時間との勝負なので kubectl の手癖づくりが本体。",
    topics: ["クラスタ構築・アップグレード", "ワークロード管理", "Service とネットワーキング", "ストレージ", "RBAC", "トラブルシューティング"] },
  CKS: { name: "Certified Kubernetes Security Specialist（CKS）", org: "CNCF", level: "上級", hours: 100, fee: "445 USD",
    links: [{ label: "認定ページ・申込", url: "https://www.cncf.io/training/certification/cks/", apply: true },
            { label: "Kubernetes ドキュメント", url: "https://kubernetes.io/ja/docs/home/" }],
    desc: "CKA 保持が前提。クラスタの堅牢化と実行時防御に踏み込む。",
    topics: ["クラスタ堅牢化", "サプライチェーンの保護", "NetworkPolicy", "PodSecurity と seccomp", "監査ログ", "ランタイム検知"] },
  GCP_DEVOPS: { name: "Google Cloud Professional Cloud DevOps Engineer", org: "Google Cloud", level: "上級", hours: 130, fee: "200 USD",
    links: [{ label: "認定ページ・申込", url: "https://cloud.google.com/learn/certification/cloud-devops-engineer", apply: true },
            { label: "Google Cloud ドキュメント", url: "https://cloud.google.com/docs" }],
    desc: "SRE の考え方（SLO・エラーバジェット・ポストモーテム）が正面から問われる稀な試験。",
    topics: ["SLI/SLO 設計", "エラーバジェット運用", "CI/CD パイプライン", "オブザーバビリティ", "インシデント管理", "ポストモーテム文化"] },

  CCNA: { name: "Cisco Certified Network Associate（CCNA）", org: "Cisco", level: "基礎", hours: 150, fee: "300 USD",
    links: [{ label: "Cisco 認定トップ", url: "https://www.cisco.com/site/us/en/learn/training-certifications/certifications/index.html", apply: true },
            { label: "Cisco Learning Network", url: "https://learningnetwork.cisco.com/" }],
    desc: "ネットワークの共通言語を身につける定番。クラウド側の理解も一段深くなる。",
    topics: ["OSI/TCP-IP モデル", "スイッチングと VLAN", "ルーティング基礎（OSPF）", "IPサービス（DHCP/NAT）", "無線LAN基礎", "自動化とプログラマビリティ"] },
  CCNP_ENCOR: { name: "CCNP Enterprise（ENCOR）", org: "Cisco", level: "上級", hours: 200, fee: "400 USD",
    links: [{ label: "Cisco 認定トップ", url: "https://www.cisco.com/site/us/en/learn/training-certifications/certifications/index.html", apply: true },
            { label: "Cisco Learning Network", url: "https://learningnetwork.cisco.com/" }],
    desc: "設計と運用の両面を深掘り。オンプレとクラウドをつなぐ役回りに効く。",
    topics: ["高度なルーティング（OSPF/BGP）", "レイヤ2冗長化", "オーバーレイ（VXLAN）", "無線アーキテクチャ", "ネットワーク保護", "自動化（Python/REST）"] },
  SEC_PLUS: { name: "CompTIA Security+", org: "CompTIA", level: "中級", hours: 90, fee: "約60,000円",
    links: [{ label: "CompTIA 日本語サイト", url: "https://www.comptia.jp/", apply: true }],
    desc: "ベンダー中立でセキュリティ全般を網羅。英語圏でも通用する共通言語になる。",
    topics: ["脅威と攻撃手法", "暗号とPKI", "アイデンティティ管理", "ネットワークセキュリティ", "リスク管理", "インシデント対応"] },
  CISSP: { name: "CISSP", org: "ISC2", level: "上級", hours: 300, fee: "749 USD",
    links: [{ label: "ISC2 公式サイト", url: "https://www.isc2.org/", apply: true }],
    desc: "8ドメインを俯瞰するマネジメント寄りの国際資格。実務経験の要件がある点に注意。",
    topics: ["セキュリティとリスク管理", "資産セキュリティ", "セキュリティアーキテクチャ", "通信とネットワーク", "IAM", "セキュリティ運用"] },

  TOUKEI2: { name: "統計検定2級", org: "日本統計学会", level: "基礎", hours: 80, fee: "7,000円",
    links: [{ label: "統計検定 公式サイト", url: "https://www.toukei-kentei.jp/", apply: true }],
    desc: "データを扱う前提となる推測統計の土台。手を動かす計算練習が中心。",
    topics: ["記述統計", "確率分布", "統計的推定", "仮説検定", "回帰分析"] },
  G_KENTEI: { name: "G検定", org: "JDLA", level: "基礎", hours: 50, fee: "13,200円",
    links: [{ label: "JDLA 公式サイト", url: "https://www.jdla.org/", apply: true }],
    desc: "AI の全体像と法務・倫理まで含む知識試験。用語の地図を作るのに向く。",
    topics: ["機械学習の基礎", "ディープラーニング手法", "AI の社会実装", "法務・倫理", "最新動向"] },
  GCP_PDE: { name: "Google Cloud Professional Data Engineer", org: "Google Cloud", level: "上級", hours: 150, fee: "200 USD",
    links: [{ label: "認定ページ・申込", url: "https://cloud.google.com/learn/certification/data-engineer", apply: true },
            { label: "Google Cloud ドキュメント", url: "https://cloud.google.com/docs" }],
    desc: "データ基盤の設計と運用。BigQuery を軸にパイプライン全体を見る。",
    topics: ["データパイプライン設計", "BigQuery 設計", "ストリーミング処理", "データガバナンス", "MLの運用", "コストと性能"] },
  JAVA_SILVER: { name: "Oracle Certified Java Programmer, Silver SE", org: "Oracle", level: "中級", hours: 80, fee: "37,730円",
    links: [{ label: "Oracle 認定資格（日本）", url: "https://www.oracle.com/jp/education/certification/", apply: true }],
    desc: "文法と例外・コレクションを正確に。書ける人ほど引っかけ対策が要る。",
    topics: ["クラスとインタフェース", "例外処理", "コレクションとジェネリクス", "ラムダとStream", "モジュールと配列操作"] },
};

export const ROADMAPS: Roadmap[] = [
  { id: "cloud", name: "クラウドインフラ", color: "#2563C9", goal: "設計から任されるクラウドエンジニアへ",
    order: ["AWS_CLF", "AWS_SAA", "AWS_SOA", "AWS_SAP", "AWS_ANS"] },
  { id: "sre", name: "SRE・プラットフォーム", color: "#E2622B", goal: "信頼性と自動化でサービスを支える",
    order: ["LINUC1", "AWS_SAA", "TF_ASSOC", "CKA", "CKS", "GCP_DEVOPS"] },
  { id: "network", name: "ネットワーク", color: "#0E8F8F", goal: "オンプレとクラウドをつなぐ設計者へ",
    order: ["CCNA", "IPA_NW", "AWS_ANS", "CCNP_ENCOR"] },
  { id: "security", name: "セキュリティ", color: "#7A45B8", goal: "守りの設計と有事対応を担う",
    order: ["IPA_SG", "SEC_PLUS", "IPA_SC", "AWS_SCS", "CISSP"] },
  { id: "data", name: "データ・AI", color: "#16A06B", goal: "データ基盤と機械学習の実装に関わる",
    order: ["TOUKEI2", "G_KENTEI", "IPA_DB", "AWS_MLA", "GCP_PDE"] },
  { id: "app", name: "アプリケーション開発", color: "#D0345B", goal: "設計まで踏み込める開発エンジニアへ",
    order: ["IPA_FE", "IPA_AP", "JAVA_SILVER", "IPA_DB", "IPA_SA"] },
];

export const KINDS: Kind[] = [
  { id: "video", name: "動画講座", icon: "▶", unit: "分", color: "#6D3FD4", hint: "Udemy・Skill Builder など", defTotal: 900 },
  { id: "book", name: "書籍・参考書", icon: "▤", unit: "ページ", color: "#C2571E", hint: "テキスト、黒本・白本など", defTotal: 400 },
  { id: "quiz", name: "問題集", icon: "✎", unit: "問", color: "#1E7BB8", hint: "Web問題集、過去問など", defTotal: 500 },
  { id: "mock", name: "模擬試験", icon: "◷", unit: "回", color: "#B03A63", hint: "本番形式のセット", defTotal: 4 },
  { id: "doc", name: "公式ドキュメント", icon: "❏", unit: "本", color: "#0F8A6A", hint: "BlackBelt、試験ガイドなど", defTotal: 12 },
  { id: "hands", name: "ハンズオン", icon: "⚒", unit: "回", color: "#8A6A11", hint: "自分で構築して試す", defTotal: 10 },
];
export const kindOf = (id: string): Kind => KINDS.find((k) => k.id === id) || KINDS[0];

export const EXP_LEVELS: ExpLevel[] = [
  { id: "none", name: "触ったことがない", desc: "用語から覚える段階", f: 1.3 },
  { id: "basic", name: "基礎知識はある", desc: "概要は把握している", f: 1.0 },
  { id: "daily", name: "業務で日常的に使う", desc: "手順に沿って作業できる", f: 0.75 },
  { id: "deep", name: "設計・障害対応まで", desc: "根拠を説明して判断できる", f: 0.6 },
];
export const expF = (id?: string): number => (EXP_LEVELS.find((e) => e.id === id) || EXP_LEVELS[1]).f;
